Repository gsg-K1-FC/E-commerce-app-Team0, pull requests merged in 2020-11, with the labels that each got.

#21 Update README.md
  README.md
Labels: In Review

#26 Add header section - home page #15
  images/Beauty.png
  images/Car.png
  images/Fashion.png
  images/Fitness.png
  images/Search icon.png
  images/Shopping-cart.png
  images/Sort.png
  images/Technology.png
  images/down arrow.png
  images/up arrow.png
  index.html
  scripts/home.js
  scripts/javascript2.js
  scripts/javascript3.js
  scripts/javascript4.js
  stylecss/style3.css
  stylecss/style4.css
  styles/home.css
  styles/style2.css
  styles/style3.css
  styles/style4.css
Labels: approved

#37 Add to cart and further enhancements
  images/down arrow.png
  images/up arrow.png
  index.html
  scripts/home.js
  styles/home.css
Labels: In Review, Technical

#35 add product design in html css
  addproduct.html
  images/avatar.png
  scripts/addproduct.js
  styles/home.css
  styles/product.css
Labels: In Review
